--Explore all objects in the database
SELECT *
FROM INFORMATION_SCHEMA.TABLES;

--Explore all coloumns in the database
select
*
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'customers'

--Explore all countries our customer comes from
Select distinct
country
from dbo.customers

--Explore all Categories the major division
select distinct
category,
subcategory,
product_name
from dim_products
order by 1,2,3

--Find the date of first and last order and how many years of sales are available?
select
Min(order_date) as first_orderdate,
Max(order_date)as Last_orderdate,
DATEDIFF(year,Min(order_date),Max(order_date)) as order_rangeyears
From fact_sales
--Find the Youngest and oldest customer
Select
Min(birthdate) as Oldestcustomer,
Datediff(year,Min(birthdate),GETDATE()) as oldestage,
Max(Birthdate) as Youngestcustomer,
Datediff(year,Max(birthdate),GETDATE()) as Youngestage
From customers


--Find Total sales
Select
sum(sales_amount) as total_sales
from fact_sales

--Find How many Items are sold
Select
sum(quantity) as total_quantity
from fact_sales

--Find the Average selling price
select
avg(price) as avg_price
From fact_sales
--Find total number of orders
select
count(distinct order_number) as total_no_of_order
from fact_sales
--Find total no of products
select
count(product_name) as total_no_of_products
from dim_products

--Find total no of customers
select
count(customer_key) as total_no_of_customer
from customers

--Find the total no of cusotmers That has placed an order
Select
count(distinct customer_key) as total_no_of_customer
from fact_sales

--Generate report that shows all Key metrics of the business
Select 'Total sales' as measure_name,sum(sales_amount) as measure_value from fact_sales
Union all
Select'Total quantity' as measure_name,sum(quantity) as measure_value from fact_sales
Union all
select 'Avg_price' as measure_name, avg(price) as measure_value From fact_sales
Union all
select 'total no of products' as measure_name,count(distinct order_number) as Measure_value from fact_sales
Union all
select 'total customers' as measure_name, count(customer_key) as Measure_value from customers

--Find total no of customers by country
Select
country,
count(distinct customer_key) as no_of_customer
From customers
Group by country
order by no_of_customer desc


--Find total customer by gender
Select
Gender,
count(distinct customer_key) as no_of_customer
From customers
Group by Gender
order by no_of_customer desc

--Find Total products by category
select
Category,
count(distinct product_key) as total_products
From dim_products
Group by category
Order by total_products desc

--What ia avg cost in each category?
select
Category,
avg(cost) as avg_cost
From dim_products
Group by category
order by avg_cost desc

--Total revenue from each category
Select
category,
sum(s.sales_amount) total_revenue
from fact_sales as s
Left join dim_products as p
on s.product_key = p.product_key
Group by category
order by total_revenue desc

--Total revenue generated by each customer
Select
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) total_revenue
from fact_sales as s
Left join customers as c
on s.customer_key = c.customer_key
Group by c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

--What is the distribution of items sold accros the country
select
c.country,
sum(s.quantity) as total_items_sold
from fact_sales as s
Left join customers as c
on s.customer_key = c.customer_key
Group by c.country
order by  total_items_sold desc

---Which 5 products generate the Highest revenue
select top 5
p.product_name,
sum(sales_amount) as total_revenue,
dense_rank()over(order by sum(sales_amount) desc)  as ranks
From fact_sales as s
Left join dim_products as p
on p.product_key = s.product_key
Group by p.product_name


--what are the five worst performing products in terms of sale
select top 5
p.product_name,
sum(sales_amount) as total_revenue,
dense_rank()over(order by sum(sales_amount))  as ranks
From fact_sales as s
Left join dim_products as p
on p.product_key = s.product_key
Group by p.product_name

--Find the top 10 customers who have generated the highest revenue
select
*
from(select
c.customer_key,
Concat(c.first_name, ' ', c.last_name) as customer_name,
sum(sales_amount) as total_revenue,
dense_rank()over(order by sum(sales_amount)desc)  as ranks
From customers as c
Left join fact_sales as s
on c.customer_key = s.customer_key
Group by c.customer_key,
c.first_name,c.last_name
 )t
where ranks <= 10

--Top 3 customers with few orders placed
select top 3
c.customer_key,
Concat(c.first_name, ' ', c.last_name) as customer_name,
Count(distinct order_number) as total_order
From customers as c
Left join fact_sales as s
on c.customer_key = s.customer_key
Group by c.customer_key,
c.first_name,c.last_name
order by total_order asc

---Analyze sales performance and customer retention over the time
select
Year(order_date) as order_year,
Sum(sales_amount) as total_sales,
count(distinct customer_key) as no_of_customer
From fact_sales
where order_date is not null
Group by Year(order_date)
order by Year(order_date)

--Calculate total sales per month,running total of sales over time
select
order_date,
total_sales,
sum(total_sales)over(order by order_date) as running_total,
avg(avg_price)over(order by order_date) as Moving_avg_price
from
(Select
datetrunc(Month,order_date)as order_date,
sum(sales_amount) as total_sales,
avg(price) as avg_price
From fact_sales
Where order_date is not null
Group by datetrunc(Month,order_date))t


/*analyze the yearly performance of the products by comparing their sales to both 
average sales performance of the product and the previous year's sales*/
 select
 order_date,
 product_name,
 total_sales,
 lag(total_sales,1,0)over(partition by product_name order by order_date) as previous_year_sales,
 avg(total_sales)over(partition by product_name) as avg_sales
 from(
 select
 year(order_date) as order_date,
 p.product_name as product_name,
 sum(sales_amount) as total_sales
 from fact_sales as s
 left join dim_products as p
 on s.product_key = p.product_key
 where order_date is not null
 group by  p.product_name,year(order_date))t
 order by product_name,order_date


 --Which categories contribute the most to overall sales?
 select
 categories,
 total_sales,
 sum(total_sales)over() as overall_sales,
 round(cast (total_sales as float)/sum(total_sales)over() *100,2) as percentages
 from(
 select
 p.subcategory as categories,
 sum(sales_amount) as total_sales
 from fact_sales as s
 left join dim_products as p
 on p.product_key = s.product_key
 group by p.subcategory)t

--/*segment products into cost ranges and count how many products fall into each segment*/
with cost_ranges as
(select
product_key,
product_name,
cost,
case when cost < 100 then 'Below 100'
     when cost between 100 and 500 then '100-500'
     when cost between 500 and 1000 then '500-1000'
     else 'Above 1000'
END COST_RANGE
from dim_products)

select
cost_range,
count(product_key) as total_products
from cost_ranges
group by cost_range
order by total_products desc

/*Group customer into three segments based on their spending behaviour:
-vip:at least 12 months of history and spending more than 5,000
-Regular:at least 12 months of history and spending  5,000 or less
-New:lifespan less than 12 months*/
with customer_spending as(
select
c.customer_key as customer_key,
sum(s.sales_amount) as total_sales,
min(s.order_date) as first_order,
Max(s.order_date) as last_order,
datediff(Month,min(s.order_date),Max(s.order_date) ) as lifespan
From fact_sales as s
left join customers as c
on c.customer_key = s.customer_key
group by c.customer_key)

,customer_seg as(
select
customer_key,
total_sales,
lifespan,
case when lifespan > = 12 and total_sales >=5000 then 'Vip'
     when lifespan > = 12 and total_sales <=5000 then 'Regular'
     Else 'New'
End customer_segment
from customer_spending)

select
customer_segment,
count(customer_key) as total_customer
from customer_seg
Group by customer_segment
order by total_customer desc


/*--Customer Report----
--Purpose: This report consolidates key customer metrics and behaviors
Highlights:
1)Gather essential fields such as Names,ages,and Transaction details.
2)Segment customer Into categories (VIP,Regular,New) and age Groups
3)Aggregate customer-level metrics:
  -Total orders
  -Total sales
  -total quantity purchased
  -Total Products
  -Lifespan(In months)
4)calculates Valuable KPI's:
   -Recency(Months since last order)
   -Avg order value
   -Avg monthly spend*/
Create View report_customer as 
with base_query as(
select
s.order_number as order_number,
s.product_key,
s.order_date as order_date,
s.sales_amount,
s.quantity,
c.customer_key as customer_key,
c.customer_number,
concat(c.first_name,' ',c.last_name) as customer_name,
Datediff(Year, c.birthdate,getdate()) as age
from fact_sales as s
left join customers as c
on c.customer_key = s.customer_key
where order_date is not null)

,customer_aggregation as(
select
customer_key,
customer_number,
customer_name,
age,
count(distinct order_number) as total_order,
sum(sales_amount) as total_sales,
sum(quantity) as total_quantity,
count(distinct product_key) as total_product,
Max(order_date) as Last_order_date,
Datediff(Month, min(order_date),Max(order_date)) as Lifespan
from base_query
group by customer_key,
customer_number,
customer_name,
age)

Select
customer_key,
customer_number,
customer_name,
age,
case
   when age < 20 then 'Under 20'
   when age between 20 and 29 then '20-29'
   when age between 30 and 39 then '30-39'
   when age between 40 and 49 then '40-49'
   else '50 and above'
End age_segment,
case when lifespan > = 12 and total_sales >=5000 then 'Vip'
     when lifespan > = 12 and total_sales <=5000 then 'Regular'
     Else 'New'
End customer_segment,
Last_order_date,
Datediff(Month,Last_order_date,Getdate()) as recency,
total_order,
total_sales,
total_quantity,
total_product,
case when total_sales = 0 then 0
else total_sales/total_order 
End avg_order_value,
case when Lifespan = 0 then total_sales
else total_sales/lifespan
End avg_monthly_spend
from customer_aggregation

/*--Product Report----
--Purpose: This report consolidates key Product metrics and behaviors
Highlights:
1)Gather essential fields such as product Names,subcategory,and cost.
2)Segment product by revenue to identify High-performer,Mid-range or Low-performers
3)Aggregate Product-level metrics:
  -Total orders
  -Total sales
  -total quantity sold
  -Total customers(Unique)
  -Lifespan(In months)
4)calculates Valuable KPI's:
   -Recency(Months since last order)
   -Avg order revenue
   -Avg monthly revenue*/
   Create View report_product as
   with product_details as (
   select
   p.product_key,
   p.product_name,
   p.category,
   p.subcategory,
   p.cost,
   Max(order_date) as last_sale_date,
   DATEDIFF(MONTH,min(order_date),Max(order_date)) as lifespan,
   count(distinct s.order_number) as total_order,
   sum(s.sales_amount) as total_sales,
   sum(s.quantity) as total_quantity_sold,
   count(distinct customer_key) as total_customers,
   round(avg(cast((s.sales_amount) as float) /Nullif(s.quantity,0)),2) as avg_selling_price
   from fact_sales as s
   Left join dim_products as p
   on p.product_key = s.product_key
   where s.order_date is not null
   group by  p.product_key,p.category,
   p.product_name,
   p.subcategory,
   p.cost)

   select
   product_key,
   product_name,
   category,
   subcategory,
   cost,
   DATEDIFF(Month,last_sale_date,getdate()) as recency_in_months,
   case when total_sales > 50000 then 'High Performer'
        when total_sales>10000 then 'Mid-range'
        else 'low-performer'
   End product_segment,
   total_order,
   total_sales,
   total_quantity_sold,
   avg_selling_price,
   --Average monthly revenue---
   case when lifespan = 0 then total_sales
        else total_sales/lifespan
   End as avg_monthly_revenue
   From product_details




